# Dependencies
highlighter:         rouge

# Permalinks
permalink:        pretty

url: https://scottchamberlain.info

# Setup
title:            Scott Chamberlain
tagline:          'homo sapien'
url:              https://scottchamberlain.info/

author:
  name:           'Scott Chamberlain'
  url:            https://twitter.com/sckottie

# paginate:         5

# Custom vars
version:          1.0.0

github:
  me:           https://github.com/sckott
  ropensci:     https://github.com/ropensci

reproduce: https://github.com/sckott/scott
