opts_chunk$set(warning=FALSE, message=FALSE, comment=NA, cache=FALSE)

---
name: where-to-publish
layout: post
title: where to publish
date: 2013-01-25
author: Scott Chamberlain
tags: 
- publishing
- open access
---

A few ecologists have discussed on their respective blogs how to decide where to publish, including [Jeremy Fox](http://dynamicecology.wordpress.com/2013/01/24/advice-how-to-decide-where-to-submit-your-paper/), [Ethan White](http://jabberwocky.weecology.org/2013/01/24/some-alternative-advice-on-how-to-decide-where-to-submit-your-paper/), and [Tim Poisot](http://timotheepoisot.fr/2013/01/24/where-to-submit/). Using the topics below that were used by Ethan, Tim, and Jeremy. 

*****************

I offer up not advice (as I'm not old and sage enough to give advice), but thoughts, on the same issue.

*****************

### Aim as high as you reasonably can.  
This is usually the advice I'm given, but I try to not pay attention to this, perhaps because I know I'm not going to be E.O. Wilson, or get a Harvard gig, and Nature or Science will probably not be accepting any of my papers as they accept very few ecology papers anyway.

### Don’t just go by journal prestige; consider “fit”.  
At the moment I do think about this, but I am chomping at the bit to not have to think about this, and go for publishing in [PloS One](http://www.plosone.org/), [PeerJ](https://peerj.com/), or [eLife](http://elife.elifesciences.org/), where there really isn't fit to consider. When reviewing papers for a journal, one of the tasks is to consider fit, so on the reviewing side, fit has to be considered. With the adoption of megajournals though, all this fit business will go away. 

### How much will it cost?  
I have never recieved a grant, so I have been scared off by big page charges, but as a student I was often able to obtain a fee waiver.

### How likely is the journal to send your paper out for external review? 
This has only happened to me once (where paper didn't get sent out for review) at American Naturalist, otherwise don't think about it much.

### Is the journal open access?  
I would publish in only OA journals if I could. The benefits are overwhelming: more people will potentially read your work - leading to more citations (if that matters to you); OA papers can be mashed up and text mined for meta-analyses, etc.; the most important of which reasons is the fact that most research is publicly funded, but publishers are making a pretty penny off of publishing without providing a whole lot of value to science (e.g., PloS may make money but all papers are OA). However, the biggest impediment to this IMHO is co-authors. That is, all papers I write are with at least a few co-authors. Everyone on the paper has to agree on the journal to submit to - and let's be honest, most academics don't get the open access movement at all. My mentors think I should shoot for high impact factor journals so I can get a good job, etc., blah blah blah.  If that is the way academia works, that sucks. The [DOAJ](http://www.doaj.org/) is a great place to look for an open access journal in your discipline. 

### Does the journal evaluate papers only on technical soundness? 
I wish this was the case, that they didn't judge on how significant your p-values are, but this will be a hard habti for scientists to not think about when reviewing a paper.

### Is the journal part of a review cascade? 
Don't care.

### Is it a society journal? 
I'll quote [Tim Poisot](http://timotheepoisot.fr/2013/01/24/where-to-submit/) on this: "Frankly my dear, I don't give a damn."

### Have you had good experiences with the journal in the past?  
Don't care.

### Is there anyone on the editorial board who’d be a good person to handle your paper? 
Don't care.

*****************

### To conclude...
The most important thing to me is moving to publishing in open access journals. If I had single authored papers, I would do this. However, as stated above, having co-authors means not getting what you want.  IMHO, if we want to change academia away from a pay-walled city that only cares about how many papers and their impact factors, we need to start ignoring the conventional wisdom that we have think about impact factor 24/7.  I will say though, that my opinion may not fit with some academics as they are trying for a hard core academic job, whereas I am trying to diversify more :)


*********
#### Get the .Rmd file used to create this post [at my github account](https://github.com/sckott/scott/blob/gh-pages/_drafts/2013-01-25-where-to-publish.Rmd) - or [.md file](https://github.com/sckott/scott/blob/gh-pages/_posts/2013-01-25-where-to-publish.md).

#### Written in [Markdown](http://daringfireball.net/projects/markdown/), with help from [knitr](http://yihui.name/knitr/).